### ISSUE TITLE
Cannot alter appearance proxy for toolbar on a webview ad

### ISSUE THREAD

**Issue by ibsh** [appnexus/mobile-sdk-ios#2]
Hey all,

I'm working on an issue at Shazam; our default appearance proxy settings for window and UIToolBar tintColor leave us with invisible controls (white on white) on the toolbar of some fullscreen web ads served through your SDK.

I believe you sent some sample code that suggested setting these properties in the adWillPresent callback (and then resetting them in adWillClose). However, that callback does not happen early enough; it seems the views in question must already have been added to the window at that point, as they do not respond to the appearance changes. I tried a few other callbacks but couldn't get one to work.

So, just a couple of quick questions:
1) Do you know of a presentation callback that fires for ads in the in-SDK browser, before that browser is added to a window?
2) Preferably, is there an exposed UIView subclass that acts as a superview for the in-SDK browser, so that I can just use appearanceWhenContainedIn during our initial group of appearance proxy calls?

Any help appreciated.

**Comment by josecu** [comment]
If I recall correctly, the problem was that the in-app browser causing the problem is not the AppNexus in-app browser, but rather the in-app browser of one of the mediated SDKs which we have no control over. This would definitely be the case if you set opensInNativeBrowser on the ANBannerAdView to YES and you still see the in-app browser with invisible controls, because we don't control the browser behavior of mediated SDKs. I suppose we could control the behavior if they also provided a "opensInNativeBrowser" flag, but I believe none do.

The issue should not happen with our in-app browser, as we hardcoded the default colors to maintain a consistent appearance independent of the appearance proxy. I haven't been able to trigger a faulty browser on my end––is it possible for you to provide a screen capture?

**Comment by ibsh** [comment]
Cool, that may well be the case. If you hardcode the appearance of your browser then it can't be that one. I'll talk to the guys here and then get back to you. Thanks.

**Comment by js** [comment]
@josecu I can. We alter `[UIToolbar appearance]` barTintColor and tintColor and I see a very blue toolbar at the bottom of your browser in the 2.8 release
![appnexusbrowser](https://cloud.githubusercontent.com/assets/23626/12449080/07842df2-bf7b-11e5-826d-75ad1b034e1e.png)

Is there anything special I need to do here? It seems like `ANAdWebViewController` is not public in the pod headers so I can't override it with -appearanceWhenContainedIn:

**Comment by josecu** [comment]
I'm not sure why the toolbar is subject to the appearance proxy since the color is hardcoded, but regardless, either of these should solve your issue:

```
[[UIToolbar appearanceWhenContainedIn:NSClassFromString(@"ANBrowserViewController"), nil]
     setBarTintColor:[UIColor colorWithRed:249.0 green:249.0 blue:249.0 alpha:1.0]];
```

```
[[UIToolbar appearanceWhenContainedInInstancesOfClasses:@[NSClassFromString(@"ANBrowserViewController")]]
     setBarTintColor:[UIColor colorWithRed:249.0 green:249.0 blue:249.0 alpha:1.0]];
```

To clarify, `ANAdWebViewController` controls the WebView, not the in-app browser. The in-app browser is controlled by `ANBrowserViewController`. Let me know if you have any questions.
