### ISSUE TITLE
Swift Package is broken

### ISSUE THREAD

**Issue by clausjoergensen** [appnexus/mobile-sdk-ios#67]
1) We can't actually consume the package because you aren't using proper semantic versioning and releasing as major.minor.patch, and as such Xcode tries to use the latest release within such a version number scheme which is 7.7.1

You need do a 7.15.0 release to fix this.

2) You apparently didn't test your package, because it's giving a warning about a unhandled file

> found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target 
> SourcePackages/checkouts/mobile-sdk-ios/sdk/sourcefiles/Viewability/OMSDK_Appnexus.xcframework

**Comment by Kowshickkarthick** [comment]
HI @clausjoergensen,
We are working on a fix for both 1 and 2 and will be releasing v7.15.1 either today or tomorrow.

In the mean time as a workaround you can do the following 
For 1: You can use `Branch: master` instead of a version as shown in the image.

<img width="981" alt="Screen Shot 2021-07-15 at 12 42 36 PM" src="https://user-images.githubusercontent.com/18311497/125825863-41a02de3-8d42-458a-9569-da2997a6e4e2.png">

For 2: We already had OMSDK_Appnexus.xcframework in the exclude path list but looks like when referencing from GitHub it is expecting a different path. This warning doesnot affect the functionality of the SDK and you can ignore it. Nevertheless we will provide an update in v7.15.1 to fix this warning as well.

**Comment by asharmaa** [comment]
Hello @clausjoergensen,

Thank you for raising the issue.

Pleased to inform you that the fix is added in [v7.15.1](https://github.com/appnexus/mobile-sdk-ios/releases/tag/7.15.1). Closing the issue.

Thanks
Abhishek
