### ISSUE TITLE
Crash when fetching ads

### ISSUE THREAD

**Issue by Bej-Technologies** [appnexus/mobile-sdk-ios#78]
I am seeing the following crash after upgrading from AppNexusSDK 7.10 -> 7.20.0:
![Screenshot 2022-04-07 at 13 54 12](https://user-images.githubusercontent.com/85553686/162192909-486d6090-10c9-4f6d-8bdd-f3b4c9e78033.png)

**Comment by Daniel-Berger** [comment]
Can you please contact support with this as well as any other details which might help us to reproduce the issue? Thank you @Bej-Technologies.

**Comment by Kowshickkarthick** [comment]
Closing this ticket due to inactivity. 
We no longer release source code updates of iOS SDK to Github. 
And this space is not monitored.
If this still needs to be worked on, Please contact your account managers or submit a ticket via the Customer Support Portal: https://help.xandr.com/ if you have any questions.
