### ISSUE TITLE
Update Google-Mobile-Ads-SDK

### ISSUE THREAD

**Issue by miquelalvarado** [appnexus/mobile-sdk-ios#82]
Hi, 

We are trying to update FirebaseAnalytics to its latest version (10.2.0) in our applications but it's not possible due to the podspec restriction that restricts Google-Mobile-Ads-SDK dependency to the 9.4.0 which uses a lower version of FirebaseAnalytics.
Would it be possible for you to update the dependency to a higher version compatible with FirebaseAnalytics 10.X? 

Thanks

**Comment by Kowshickkarthick** [comment]
Closing this ticket due to inactivity. 
We no longer release source code updates of iOS SDK to Github. 
And this space is not monitored.
If this still needs to be worked on, Please contact your account managers or submit a ticket via the Customer Support Portal: https://help.xandr.com/ if you have any questions.
