### ISSUE TITLE
MRAID support

### ISSUE THREAD

**Issue by dziwiedz** [appnexus/mobile-sdk-ios#83]
Hi!

How I can display mraid ad type? 
I've read that I can request ad with placemnt id 2579103 but it's not returning anything, also for the appstore sdk app.
https://docs.xandr.com/en-US/bundle/industry-reference/page/mraid-and-mobile-video-tutorial.html

**Comment by Kowshickkarthick** [comment]
Closing this ticket due to inactivity. 
We no longer release source code updates of iOS SDK to Github. 
And this space is not monitored.
If this still needs to be worked on, Please contact your account managers or submit a ticket via the Customer Support Portal: https://help.xandr.com/ if you have any questions.
