### ISSUE TITLE
Swift Package definition broken in 8.8.0, with invalid OMSDK_Appnexus.xcframework links

### ISSUE THREAD

**Issue by pyrtsa** [appnexus/mobile-sdk-ios#84]
The latest 8.8.0 release moved OMSDK_Appnexus.xcframework to dynamic and static counterparts.

I see that changes were done to support it in CocoaPods, but the SwiftPM package definition was left unchanged, [still linking to `sdk/sourcefiles/Viewability/OMSDK_Appnexus.xcframework`](https://github.com/appnexus/mobile-sdk-ios/blob/8.8.0/Package.swift#L30-L42).

Trying to update appnexus/mobile-sdk-ios to 8.8.0 breaks the package graph in SwiftPM, failing to even start the build.

**Comment by Kowshickkarthick** [comment]
Closing this ticket due to inactivity. 
We no longer release source code updates of iOS SDK to Github. 
And this space is not monitored.
If this still needs to be worked on, Please contact your account managers or submit a ticket via the Customer Support Portal: https://help.xandr.com/ if you have any questions.
